### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by sysdl132** [SheepTester/sheeptester.github.io#11]
I can use F12 tools:
``
clicks = [number]
``
to change clicks.
![image](https://user-images.githubusercontent.com/54708046/75131362-bae54380-570d-11ea-83c6-7b2a03e98e95.png)
Do you have some idea to fix it(because when I playing MARS,I can't change the number by using F12.)

**Comment by sysdl132** [comment]
![image](https://user-images.githubusercontent.com/54708046/75140289-87181700-5729-11ea-8190-c68959a7c926.png)
Another problem:What happened of this ball?(platformre)

**Comment by sysdl132** [comment]
solved...like my internet error...

**Comment by sysdl132** [comment]
Can you make an offline version like this?
![image](https://user-images.githubusercontent.com/54708046/75638963-6ee45280-5c69-11ea-8fdc-b3e1db78f59e.png)
The offline version maybe will be useful.
(tip:my APP is used NWJS sdk kit)

**Comment by sysdl132** [comment]
![image](https://user-images.githubusercontent.com/54708046/75668731-be03a500-5cb4-11ea-9074-2883ac9ffcf9.png)
still not found after submitting.

**Comment by sysdl132** [comment]
note:if you think this issue is no longer to use,you can close it.

**Comment by SheepTester** [comment]
I don't receive notifications for issues on this repository for some reason

> Do you have some idea to fix it(because when I playing MARS,I can't change the number by using F12.)

In Mars, you can change the number of initians by setting `stats.initians`

I don't really think it's a problem because there's no global leaderboard or anything, so cheating only affects the cheater

> Can you make an offline version like this?

You could use the "Cache files" button on [/all/](https://sheeptester.github.io/all/) to cache relevant files offline, or you could download index.html, style.css, and main.js in this repository

> ![image](https://user-images.githubusercontent.com/54708046/75668731-be03a500-5cb4-11ea-9074-2883ac9ffcf9.png)
> still not found after submitting.(platformre)

This should be fixed now!

**Comment by sysdl132** [comment]
OK.I will look up it later.
